export default {
  authName: "#auth_name",
  authUrl: "#url",
  authApiKey: "#apikey",
  proceedBtn: ".btn-primary",
  navigateToDeploymentScreen: {
    deploymentBtn: "a.nav-link:contains(Deployments)",
    "@getAllApps": 200,
    createBtn: ".create-object",
    createNewBtn: "button.zeroPage_Btn",
    deploymentType: "div.select-app-type-container a"
  },
  fillBasicInfoScreen: {
    continuenotDisabled: ".btn-continue",
    settingBtn: ".advance-settings",
    customFlowsBtn: "span.slider",
    homePageUrlnotEmpty: ".text-field-container input#homepage_url",
    continue2notDisabled: ".btn-continue",
    connectorAuthDropdown: {
      menu: "div.dynamic-dropdown__control",
      option: "div.dynamic-dropdown__option"
    },
    continueAssertText: ".btn-continue",
    radioBtn: "[type='radio']"
  },
  fillMarketPlaceAppearnceScreen: {
    "@getBundles": 200,
    title: "#title",
    description: "#header_text",
    continueBtnForce: ".btn-continue",
  },
  selectColorForMarketPlaceLogo: {
    colorBox: "input[name='top_menu_color']",
    continueBtnForce: ".btn-continue",
    "@UpdateBundles": 200,
    continue2BtnForce: ".btn-continue",
  },
  fillCTA_BarInfo: {
    actionTitleTextBox: "#action_title",
    actionDescriptionTextBox: "#action_description",
    continueBtnForce: ".btn-continue",
    "@UpdateBundles": 200,
  },
  fillSocailMediaLinks: {
    continueBtnForce: "button.btn-continue",
    "@UpdateBundles": 200,
  },

  v3: {
    deploymentBtn: ".nav-item:nth-child(3) > .nav-link",
    createBtn: ".create-object",
    urlTextBox: "#app_url",
    colorBox: "input.form-control",
    continueBtn: ".btn-continue",
    title: "#title",
    description: "#header_text",
    iconUpload: ".app-icon-upload-text",
    actionTitleTextBox: "#action_title",
    actionDescriptionTextBox: "#action_description",
    baseUrl: "#integry_url",
    appCardBtn: ".directory-name > .link-icon",
  },
  addingCard: {
    appCardBtn: ".bundle-card .info",
    sideBar: "#sidebar-nav .list-group-item",
    searchBar: ".search-bar",
    addFlow: ".card-type img[alt='add-icon']",
    successMsg: ".Toastify__toast-body",
    categoryAdd: ".search-result img[alt='add-icon']",
    newCategory: "img[alt='add-icon']",
    newIcon: ".add-card-under-category-button img[alt='plusIcon']",
    flowCard: ".cards-container-v3 .title",
    name: "#name",
    switchBtn: ".switch #show_product_page",
    pageTitle: ".page-heading",
    description: "#description",
  },
  Sdk: {
    createBtn: ".create-object",
    createFlowBtn: ".create-object-content",
    titleText: "#name",
    liveSwitchBtn: ".switch",
    createGuidedFlowBtn: "button[type='button']",
    flowTitleText: "#title",
    flowDescriptionText: "#description",
    searchBox: ".search-bar",
    selectAppCard: "div.app-tile div.app-name",
    triggerBtn: ".css-1wy0on6",
    SelectTriggerOption: ".css-1ksyk61-option",
    radioBtn: "#account-radio-2558-0",
    passwordPreview: ".toggleView",
    previewBtn: ".btn-preview",
    saveBtn: ".btn-save",
    successMsg: ".Toastify__toast-body",
    continueBtn: ".dot-loader-container directory-next-button-v3",
  },
  marketPlace: {
    selectMp: "div.bundle-card",
    priviewLink: "div.preview-link a",
    topMenuBar: "#top-menu-bar"
  },

  signinAndout: {
    marketplaceBtn: "div#top-menu-bar",
    signinBtn: '#top-menu-bar a[onclick="openAuthModal()"]',
    authBtn: "div.styles-module_button__3PLW1",
    nextBtn: "button.styles-module_button__osBYJ",
  },
};
