export default {
    containerHeading1: 'thead > tr > :nth-child(1)',
    containerHeading2: 'thead > tr > :nth-child(2)',
    //ContainerHeading3: 'thead > tr > :nth-child(3)',
    containerHeading4: 'thead > tr > :nth-child(3)',
    containerHeading5: 'thead > tr > :nth-child(4)',
    containerHeading6: 'thead > tr > :nth-child(5)',
    containerHeading7: 'thead > tr > :nth-child(6)',
    containerHeading8: 'thead > tr > :nth-child(7)',
    containerHeading9: 'thead > tr > :nth-child(8)',
    search: '#integry-search-bar',
    noSearchResult: '.view-record-not-found__placeholder > p',
    totalRows: ':nth-child(n)> :nth-child(1) >.integry-table--column',
    filter: '.view-filters__pills > .MuiButtonBase-root',
    filterApplyButton: '.view-drawer__actions--bottom > .view-drawer__actions__cta',
    firstFilterPill: '.integry-grouped-filter-pills > :nth-child(3)',
    secondFilterPill: '.integry-grouped-filter-pills > :nth-child(2)',
    closeSecondFilter: ':nth-child(2) > .integry-filter-pill__actions > img',
    clearAllFilters: '.integry-grouped-filter-pills__clear-cta',
    errorNotficationMessage: '.info-message',
    newRow: ':nth-child(3) > :nth-child(1) > .integry-table--column > div',

    previewSetup: {
        previewSetupButton: '.meatballs-menu__items > :nth-child(2)',
        previewSetupDescription: '.int-prev-setup__modal--header__subtitle > :nth-child(1)',
        versionLabel: '.version-selector__label',
        stepHeading: '.styles-module_textDiv__2TsUd',
        connectedAccountOfApp: '.styles-module_text__Jq7I0',
        topNavigation2ndTab: ':nth-child(2) > .styles-module_navItem__ozaSU > .styles-module_navItemContent__3UHl8 > p',
        dropdown: '.styles-module_selected__nLzUy',
        nextButton: ':nth-child(2) > .styles-module_button__osBYJ',
        versionDropdown: '.version-selector-drpdwn__arrow',
        initailVersion: '.version-selector-drpdwn__options > :nth-child(2)',
        changedTag: '.styles-module_textDiv__2TsUd > .styles-module_tag__1g320',
        previewSetupButtonOnRunsPage: '[style="color: rgb(66, 80, 240); margin-right: 14px; font-family: Inter; font-style: normal; font-weight: 400; font-size: 12px; line-height: 15px; text-align: right; text-transform: none;"]',
        subheaidng: ':nth-child(1) > [style="position: relative;"] > .styles-module_listboxGroupWrapper__1Kt5M > fieldset > .styles-module_label__PbFlo > label > :nth-child(1)',
    },

    allIntegrations: {
        integrationsView: ':nth-child(1) > :nth-child(3) > .integry-table--column > a',
        flowIcon: '.integry-filter-pill__actions > img',
        completedStatusRadioButton: ':nth-child(8) > .integry-radio-selection > :nth-child(2) > .integry-radio-selection__input',
        enabledRadioButton: ':nth-child(10) > .integry-radio-selection > :nth-child(2) > .integry-radio-selection__input',
        meatBall: '.integry-meatballs-menu > img',
        disableEnableButton: '.meatballs-menu__items > :nth-child(1)',
        toaste: '.Toastify__toast',
        closeToast: '.custom-close-toast',
        integrationID: ':nth-child(1) > .integry-table--column > div',
        userID: ':nth-child(2) > .integry-table--column > div',
        //UserAuth: ':nth-child(3) > .integry-table--column',
        dateCreated: ':nth-child(3) > .integry-table--column > div',
        lastRunStart: ':nth-child(4) > .integry-table--column > div',
        lastRunStatus: '.integry-table--column > .integry-tag',
        integrationStatus: ':nth-child(6) > .integry-table--column > div',
        intCount: 'thead > tr > :nth-child(7)',
        pages: '#currentPages',
        viewRunsButton: '[style="display: grid; grid-template-columns: auto auto; gap: 11px;"] > .MuiButtonBase-root',
        newRow2: ':nth-child(6) > :nth-child(1) > .integry-table--column > div',
        newRow3: ':nth-child(7) > :nth-child(1) > .integry-table--column > div'
    },

    metaData: {
        flowIcon: '.integry-grouped-info--avatar',
        flowNameHeading: '.integry-grouped-info--profile__label',
        flowName: '.integry-grouped-info--profile__title',
        flowIDHeading: ':nth-child(2) > .attribute--title',
        flowID: ':nth-child(2) > .attribute--render',
        flowStatusHeading: ':nth-child(4) > .attribute--title',
        flowStatus: ':nth-child(4) > .attribute--render > .integry-tag',
        integrationHeading: '.integry-grouped-info--meta__heading',
        integrationIDHeading: ':nth-child(1) > .attribute--title',
        userIDHeading: ':nth-child(3) > .attribute--title',
        userAuthHeading: ':nth-child(5) > .attribute--title',
        dateCreatedHeading: ':nth-child(7) > .attribute--title',
        lastRunStartHeading: ':nth-child(9) > .attribute--title',
        lastRunStatusHeading: ':nth-child(11) > .attribute--title',
        integrationStatusHeading: ':nth-child(13) > .attribute--title',
        integrationID: '.attribute--render > span',
        userID: ':nth-child(3) > .attribute--render',
        dateCreated: ':nth-child(7) > .attribute--render > div',
        lastRunStart: ':nth-child(9) > .attribute--render > div',
        lastRunStatus: '[data-tip="true"] > .integry-tag',
        integrationStatus: ':nth-child(13) > .attribute--render',
        integrationIDStepPage: ':nth-child(1) > .integry-grouped-info--meta__content > :nth-child(1) > .attribute--render',
        runsHeading: ':nth-child(2) > .integry-grouped-info--meta__heading',
        runIDHeading: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(1) > .attribute--title',
        runID: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(1) > .attribute--render',
        triggerAppHeading: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(3) > .attribute--title',
        triggerNameHeading: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(5) > .attribute--title',
        triggerTypeHeading: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(7) > .attribute--title',
        startTimeHeading: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(9) > .attribute--title',
        durationHeading: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(11) > .attribute--title',
        runStatusHeading: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(13) > .attribute--title',
        triggerApp: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(3) > .attribute--render',
        triggerName: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(5) > .attribute--render',
        triggerType: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(7) > .attribute--render',
        startTime: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(9) > .attribute--render > div',
        duration: ':nth-child(2) > .integry-grouped-info--meta__content > :nth-child(11) > .attribute--render',

        status: ':nth-child(13) > .attribute--render > .integry-tag',


    },
    allRuns: {
        containerHeading1: 'thead > tr > :nth-child(1)',
        containerHeading2: 'thead > tr > :nth-child(2)',
        containerHeading3: 'thead > tr > :nth-child(3)',
        containerHeading4: 'thead > tr > :nth-child(4)',
        containerHeading5: 'thead > tr > :nth-child(5)',
        containerHeading6: 'thead > tr > :nth-child(6)',
        containerHeading7: 'thead > tr > :nth-child(7)',
        containerHeading8: 'thead > tr > :nth-child(8)',
        containerHeading9: 'thead > tr > :nth-child(9)',
        runsPageHeading: '[style="display: flex; flex-direction: row; align-items: center; justify-content: space-between;"] > div',
        runsPageSubHeading: '.view-sub-heading',
        hoverInternalSteps: '.integry-checkbox-selection__label',
        tooltipInternalSteps: '.tooltip-inner > div',
        //internalStepCheckBox: '.custom-checkbox',
        internalStepCheckBox: '.integry-checkbox-selection > .integry-control-group',
        clearSearch: '.search-icon',
        filterCompletedRadioButton: ':nth-child(6) > .integry-radio-selection > :nth-child(2) > .integry-radio-selection__input',
        filter2xxRadiobutton: ':nth-child(8) > .integry-radio-selection > :nth-child(2) > .integry-radio-selection__input',
        triggeredAppLogo: ':nth-child(2) > .integry-table--column > div > img',
        triggeredApp: '.integry-table--column > div > span',
        triggerName: ':nth-child(3) > .integry-table--column > div',
        triggerType: ':nth-child(4) > .integry-table--column > div',
        startTime: ':nth-child(5) > .integry-table--column > div',
        duration: ':nth-child(6) > .integry-table--column > div',
        status: ':nth-child(7) > .integry-table--column > div',
        networkCode: '.integry-table--column > span',
        stepsViewButton: '[style="display: grid; grid-template-columns: auto auto; gap: 11px;"] > .MuiButtonBase-root'

    },
    steps: {
        stepPageHeading: '.view-heading > div',
        stepHeading: '.view-sub-heading',
        stepIDHeading: '.div-header > :nth-child(1)',
        stepAppHeading: '.div-header > :nth-child(2)',
        stepNameHeading: '.div-header > :nth-child(3)',
        startTimeHeading: '.div-header > :nth-child(4)',
        duration: '.div-header > :nth-child(5)',
        status: '.div-header > :nth-child(6)',
        networkCode: '.div-header > :nth-child(7)',
        triggerStepID: ':nth-child(1) > .div-row > div',
        triggerStepApp: ':nth-child(1) > .div-row > :nth-child(2) > :nth-child(1) > .div-column__group > span',
        triggerStepName: ':nth-child(1) > .div-row > div',
        triggerStepTime: ':nth-child(1) > .div-row > :nth-child(4) > div',
        triggerStepDuration: ':nth-child(1) > .div-row > :nth-child(5) > div',
        triggerStepStatus: ':nth-child(1) > .div-row > :nth-child(6) > .integry-tag',
        triggerStepNetworkCode: '[style="justify-content: space-between; color: rgb(116, 157, 72);"] > div',
        ifStepID: ':nth-child(2) > .div-row > div',
        ifStepApp: ':nth-child(2) > .div-row > :nth-child(2) > :nth-child(1) > .div-column__group > span',
        ifStepName: ':nth-child(2) > .div-row > div',
        ifStepTime: ':nth-child(2) > .div-row > :nth-child(4) > div',
        ifStepDuration: ':nth-child(2) > .div-row > :nth-child(5) > div',
        ifStepStatus: ':nth-child(2) > .div-row > :nth-child(6) > .integry-tag',
        ifStepNetworkCode: '[style="justify-content: space-between; color: rgb(240, 92, 66);"] > div',
        expandSteps: '.expand-sub-steps',
        actionStepID: '.sub-table > .div-table > .div-body > .row-container > .div-row > div',
        actionStepApp: '.sub-table > .div-table > .div-body > .row-container > .div-row > :nth-child(2) > :nth-child(1) > .div-column__group > span',
        actionStepName: '.sub-table > .div-table > .div-body > .row-container > .div-row > div',
        actionStepTime: '.sub-table > .div-table > .div-body > .row-container > .div-row > :nth-child(4) > div',
        actionStepDuration: '.sub-table > .div-table > .div-body > .row-container > .div-row > :nth-child(5) > div',
        actionStepStatus: '.sub-table > .div-table > .div-body > .row-container > .div-row > :nth-child(6) > .integry-tag',
        actionStepNetworkCode: '.sub-table > .div-table > .div-body > .row-container > .div-row > div',
        triggerPayloadButton: '[style="justify-content: space-between; color: rgb(116, 157, 72);"] > .MuiButtonBase-root',
        requestTab: '.tab-section > :nth-child(1)',
        responseTab: '.tab-section > :nth-child(2)',
        headerTitle: '.header-section > .heading-div > .heading',
        bodyTitle: '.body-section > .heading-div > .heading',
        toggleSlider: '.slider',
        toggle: '.switch',
        body: '.body-editor > #ace-editor > .ace_scroller > .ace_content',
        URLVerb: '.url-verb',
        URLValue: '.url-value > input',
        header: '.headers-editor > #ace-editor > .ace_scroller > .ace_content',
        objectTab: '.tab-section > :nth-child(3)',

        ifPayloadButton: '[style="border-radius: 6px 6px 0px 0px;"] > [style="justify-content: space-between; color: rgb(240, 92, 66);"] > .MuiButtonBase-root',
        ifPayloadButtonHide: '[style="border-radius: 6px 6px 0px 0px; border-bottom: none;"] > [style="justify-content: space-between; color: rgb(240, 92, 66);"] > .MuiButtonBase-root',
        actionPayloadButton: '.sub-table > .div-table > .div-body > .row-container > .div-row > [style="justify-content: space-between; color: rgb(240, 92, 66);"] > .MuiButtonBase-root',

    }


}