runtime: php55
api_version: 1
service: webapp

handlers:
- url: /static
  static_dir: static

- url: /(.*\.(ico|json|js))$
  static_files: \1
  upload: .*\.(ico|json|js)$

- url: /.*
  script: index.html
